### ISSUE TITLE
Allow multiple projectKey values

### ISSUE THREAD

**Issue by abhay-groww** [fgiuliani/jira-issue-key-checker#1]
It would be nice to include more than one projectKey so that one of a predefined set of projects is allowed and nothing else. For example:
```
steps:
      - uses: [your-user]/[your-action-repository]@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          jira-prefixes: ["ABC","EFG"]
```
